version: '3'

services:
  database:
    image: 'mysql/mysql-server:8.0'
    container_name: drm-database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "videos"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "docker"
      MYSQL_ROOT_PASSWORD: "1NfHJ9WK*X2<YI`Z%"
      MYSQL_PASSWORD: "NfHJ9WK*X2<YI`Z%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - drmServerNetwork
  redis:
    image: redis:alpine
    container_name: drm-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass fXhHKLQgT7X5
    volumes:
      - 'redis_data:/data'
    ports:
      - "6379:6379"
    networks:
      - drmServerNetwork
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
networks:
  drmServerNetwork:
    driver: bridge